// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compute_weight
double compute_weight(DataFrame const& instance, IntegerVector const& interaction, List const& map, double radius);
RcppExport SEXP baseRIT_compute_weight(SEXP instanceSEXP, SEXP interactionSEXP, SEXP mapSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame const& >::type instance(instanceSEXP);
    Rcpp::traits::input_parameter< IntegerVector const& >::type interaction(interactionSEXP);
    Rcpp::traits::input_parameter< List const& >::type map(mapSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    __result = Rcpp::wrap(compute_weight(instance, interaction, map, radius));
    return __result;
END_RCPP
}
// print_test
void print_test(DataFrame const& data);
RcppExport SEXP baseRIT_print_test(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame const& >::type data(dataSEXP);
    print_test(data);
    return R_NilValue;
END_RCPP
}
// print_test2
void print_test2(DataFrame const& data, int idx0, int idx1, int nb_class);
RcppExport SEXP baseRIT_print_test2(SEXP dataSEXP, SEXP idx0SEXP, SEXP idx1SEXP, SEXP nb_classSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame const& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type idx0(idx0SEXP);
    Rcpp::traits::input_parameter< int >::type idx1(idx1SEXP);
    Rcpp::traits::input_parameter< int >::type nb_class(nb_classSEXP);
    print_test2(data, idx0, idx1, nb_class);
    return R_NilValue;
END_RCPP
}
// cpp_naive_RIT
Rcpp::List cpp_naive_RIT(Rcpp::List const& datas, Rcpp::NumericVector const& theta, int n_trees, int depth, int split_nb, int branch, int min_inter_sz, int L, bool es);
RcppExport SEXP baseRIT_cpp_naive_RIT(SEXP datasSEXP, SEXP thetaSEXP, SEXP n_treesSEXP, SEXP depthSEXP, SEXP split_nbSEXP, SEXP branchSEXP, SEXP min_inter_szSEXP, SEXP LSEXP, SEXP esSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List const& >::type datas(datasSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_trees(n_treesSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type split_nb(split_nbSEXP);
    Rcpp::traits::input_parameter< int >::type branch(branchSEXP);
    Rcpp::traits::input_parameter< int >::type min_inter_sz(min_inter_szSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< bool >::type es(esSEXP);
    __result = Rcpp::wrap(cpp_naive_RIT(datas, theta, n_trees, depth, split_nb, branch, min_inter_sz, L, es));
    return __result;
END_RCPP
}
