# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_weight <- function(instance, interaction, map, radius) {
    .Call('baseRIT_compute_weight', PACKAGE = 'baseRIT', instance, interaction, map, radius)
}

print_test <- function(data) {
    invisible(.Call('baseRIT_print_test', PACKAGE = 'baseRIT', data))
}

print_test2 <- function(data, idx0, idx1, nb_class) {
    invisible(.Call('baseRIT_print_test2', PACKAGE = 'baseRIT', data, idx0, idx1, nb_class))
}

cpp_naive_RIT <- function(datas, theta, n_trees, depth, split_nb, branch, min_inter_sz, L, es) {
    .Call('baseRIT_cpp_naive_RIT', PACKAGE = 'baseRIT', datas, theta, n_trees, depth, split_nb, branch, min_inter_sz, L, es)
}

